<?php
include_once('./simple_html_dom.php');
include_once( "./classes/Model.php" );
include_once( './classes/View.php' );
include_once( "./classes/Test.php" );
$my_teams = new Test();
//$my_teams->scrapeMiamiDolphins();
//$my_teams->buffaloBills();
//$my_teams->miamiDolphins();
//$my_teams->newEnglandPatriots();
//$my_teams->newYorkJets();
//$my_teams->baltimoreRavens();
//$my_teams->cincinnatiBengals();
//$my_teams->clevelandBrowns();
//$my_teams->pittsburghSteelers();
//$my_teams->houstonTexans();
//$my_teams->indianapolisColts();
//$my_teams->jacksonvilleJaguars();
//$my_teams->tennesseeTitans();
//$my_teams->denverBroncos();
//$my_teams->kansascityChiefs();
//$my_teams->oaklandRaiders();
//$my_teams->sandiegoChargers();
//$my_teams->dallasCowboys();
//$my_teams->newyorkGiants();
//$my_teams->philadelphiaEagles();
//$my_teams->washingtonRedskins();
//$my_teams->chicagoBears();
//$my_teams->detroitLions();
//$my_teams->greenbayPackers();
//$my_teams->minnesotaVikings();
//$my_teams->atlantaFalcons();
//$my_teams->carolinaPanthers();
//$my_teams->neworleansSaints();
//$my_teams->tampabayBuccaneers();
//$my_teams->arizonaCardinals();
//$my_teams->stlouisRams();
//$my_teams->sanfrancisco49ers();
//$my_teams->seattleSeahawks();
//$result = $my_teams->returnResult();
//echo $result;
$my_teams->getVideos( "Cincinnati+Bengals" );

